{% set name = "mo-logs" %}
{% set version = "8.531.24035" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz
  sha256: 7d5e6076bc4de3992c7d10e3cfabdb96c42444eaf2302d6f573ad534e8ea2cf2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.531.24035
    - mo-future ==7.531.24035
    - mo-imports ==7.531.24035
    - mo-kwargs ==7.531.24035

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
