{% set name = "mo-logs" %}
{% set version = "8.685.25166" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 955d4a1011cc11e9c62650e749fa1407d92b97788d5a68989e195d7c0a5aa5db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - mo-dots ==10.685.25166
    - mo-future ==7.685.25166
    - mo-imports ==7.685.25166
    - mo-kwargs ==7.685.25166

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
