{% set name = "mo-logs" %}
{% set version = "8.672.25036" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 44fa0bd2f4c134ef79eaa7bcef7f42887776ef441b849b27b8107bd7876f700d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - mo-dots ==10.672.25036
    - mo-future ==7.672.25036
    - mo-imports ==7.672.25036
    - mo-kwargs ==7.672.25036

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
