{% set name = "mo-logs" %}
{% set version = "8.703.26061" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8285b1e772bc02a5f6e0d5ab6a5e57424f9cc3132b96933f38deb0349a572795

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - mo-dots ==10.685.25166
    - mo-future ==7.685.25166
    - mo-imports ==7.685.25166
    - mo-kwargs ==8.703.26061

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
