{% set name = "mo-logs" %}
{% set version = "3.143.20326" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz
  sha256: 266a980122ee002b0682b1404140f2903f7ba801d122d9b448a287848269a9b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots 3.141.20326
    - mo-future 3.136.20306
    - mo-imports >=3.108.20292
    - mo-kwargs >=3.93.20259

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
